### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Bitumelourd** [RMeli/spyrmsd#88]
**Describe the bug**

Hello

I am trying to use spyrmsd as a standalone tool using the prompt:
```bash
python -m spyrmsd molAtest.xyz molBtest.xyz
```

`molA.xyz` and `molB.xyz` can be found in `mol_test.zip`.

**To Reproduce**

run `python -m spyrmsd molAtest.xyz molBtest.xyz`

**Expected behavior**

```
Traceback (most recent call last):
  File "/home/ogayraud/miniconda3/lib/python3.9/runpy.py", line 197, in _run_mod
    return _run_code(code, main_globals, None,
  File "/home/ogayraud/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ogayraud/miniconda3/lib/python3.9/site-packages/spyrmsd/__main__.p
    ref = io.loadmol(args.reference)
  File "/home/ogayraud/miniconda3/lib/python3.9/site-packages/spyrmsd/io.py", li
    mol = load(fname)
  File "/home/ogayraud/miniconda3/lib/python3.9/site-packages/spyrmsd/optional/r
    raise NotImplementedError
NotImplementedError
```

**Environment**
 - OS: CentOS Linux 7 (Core)
 - Python: Python 3.9.16
 - Package Manager [e.g. `pip`, `conda`]: pip 23.1.2 and conda 23.3.1

**Additional Context**

I'm not sure what file format Spyrmsd expects and this error is probably due to misuse of Spyrsmd.

[mol_test.zip](https://github.com/RMeli/spyrmsd/files/12892224/mol_test.zip)

**Comment by RMeli** [comment]
Hi @Bitumelourd, thank you for reporting the issue. Which library are you using for molecular I/O? Your output is truncated, but I assume it is RDKit.

RDKit currently supports only `.sdf`, `.mol2`, and `.pdb` files:

https://github.com/RMeli/spyrmsd/blob/b5532dd1b677a686c9d31c7bf39446e0a66e0af8/spyrmsd/optional/rdkit.py#L50-L67

You are trying to use `.xyz` files, which are not supported. The error message is not clear at all, so I'll open an issue to improve it!

I don't currently support all the formats that RDKit supports, but I think `.xyz` is not supported by RDKit either. The main reason is that `.xyz` does not contain any bond information. This also means that `spyrmsd` can't apply symmetry corrections based on graph isomorphism.

If you want to use `spyrmsd` with `.xyz` files I suggest to use Open Babel instead, and use the `--nosym` option.

**Comment by Bitumelourd** [comment]
Thanks for the quick answer. This is totally this. Now I'm moving to use it as a module and convert .xyz file to .mol file using RDTkit. I have made a quick script :

`#!/usr/bin/env python3

import numpy as np
import sys
from spyrmsd import rmsd
from rdkit.Chem import MolFromSmiles, rdmolops
from rdkit.Chem import AllChem, AddHs
from rdkit import Chem

file_name_1 = sys.argv[1]
file_name_2 = sys.argv[2]

def extract_atomic_coordinates(file_name):
    with open(file_name, 'r') as file:
        lines = file.readlines()[2:]

        atomic_coordinates = []
        for line in lines:
            if line.strip() and line.split()[0] != 'H':
                parts = line.split()
                x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
                atomic_coordinates.append([x, y, z])

    return np.array(atomic_coordinates)

raw_mol = Chem.MolFromXYZFile(f'{file_name_1}')
mol = Chem.Mol(raw_mol)

a = extract_atomic_coordinates(file_name_1)
b = extract_atomic_coordinates(file_name_2)

coordinates_1 = np.array(a)
coordinates_2 = np.array(b)

# Print atom ordering
print(f'Ordering={[atom.GetSymbol() for atom in mol.GetAtoms()]}')
elements = np.array([atom.GetSymbol() for atom in mol.GetAtoms()])

# Print the adjacency matrix
A=rdmolops.GetAdjacencyMatrix(mol)
print(f'A={A}')

rmsd = rmsd.symmrmsd(
            coordinates_1,
            coordinates_2,
            elements,
            elements,
            A,
            A,
            center=True, minimize=True
        )
`

and I'm now facing this error:

`/home/miniconda3/lib/python3.9/site-packages/spyrmsd/graphs/nx.py:42: UserWarning: Disconnected graph detected. Is this expected?`

Am I doing something wrong?

**Comment by RMeli** [comment]
Nothing wrong from a quick look. However, as I mentioned before, `.xyz` files do not contain any bond information. If you look at the adjacency matrix, it is all zero (or eventually the identity), because there are no known connection between the atoms. 

This means that when using `rmsd.symmrmsd`, the graph constructed for symmetry correction only has a bunch of nodes (the atoms) and not vertices (no bonds). Therefore, it is a disconnected graph. 

In this case you can call `rmsd.rmsd`, since it's not possible to apply symmetry corrections without the bonds. `rmsd.symmrmsd` should still give you the same result, it's just needlessly more expensive and prints the `UserWarning` to let you know that something is not totally expected: a single molecule is usually represented by a connected graph.

If you want a bit more information about symmetry-corrected RMSD with graph-isomorphism, I'd suggest to have a look at the [spyrmsd paper](https://doi.org/10.1186/s13321-020-00455-2), if you haven't done so already.

**Comment by RMeli** [comment]
BTW, if you are parsing the `.xyz` manually, there is no reason to use RDKit. That's why RDKit is an optional dependency: `spyrmsd` is supposed to be lightweight and internally requires only `numpy` arrays. You can parse the element name from the file too (in a separate array), and the adjacency matrix is not needed in this case because there are no bonds.

Something like the following (untested):
```python
#!/usr/bin/env python3

import numpy as np
import sys
from spyrmsd import rmsd

file_name_1 = sys.argv[1]
file_name_2 = sys.argv[2]

def parse_xyz(file_name):
    with open(file_name, 'r') as file:
        lines = file.readlines()[2:]

        elements = [ ]
        atomic_coordinates = []
        for line in lines:
            e, x, y, z = line.strip()
            if e != 'H':
                elements.append(e)
                atomic_coordinates.append([float(x), float(y), float(z)])

    return np.array(elements), np.array(atomic_coordinates)

elements1, coordinates_1 = parse_xyz(file_name_1)
elements2, coordinates_2 = parse_xyz(file_name_2)

# Maybe check that elements1 and elements2 are the same

rmsd = rmsd.rmsd(
            coordinates_1,
            coordinates_2,
            elements1,
            elements2,
            center=True, minimize=True
        )
```

**Comment by davidoskky** [comment]
You can use openBabel to directly parse xyz documents. I would not advise this, since the connectivity is implied and this can be done incorrectly. In your case the bonds seem to be correctly implied by openBabel. Your xyz files are not correctly redacted: you are missing the first row in which you define how many atoms are contained in the document. While not strictly necessary, this line is useful to identify documents which contain errors and a significant portion of software (including openBabel) will not accept the document unless it's present.

Since I see you're using conda, you can support this behavior by simply installing openBabel
```
conda install -c conda-forge openbabel
```

Then you can execute
```
python -m spyrmsd molAtest.xyz molBtest.xyz
``` 
which will return you an RMSD of 0.15241

I would not use the --nosym option as at least in this case it appears that atoms are not correctly numbered and using it leads to a result of: 1.07270
I didn't manually calculate the RMSD value, but looking at the structures the first one appears to be the most plausible among the two.

**Comment by RMeli** [comment]
> I am totally new to python and coding as I come from the experimental field, so my questions may be naive and my vocabulary may be incorrect.

No need to justify your questions! I'm happy to answer any question if I can. The initial error you reported was clear to me, but the error message was completely rubbish from an user perspective. I will improve it, and that's thanks to you.

> The problem I'm facing is that I have a program that generates conformers, I then try to eliminate duplicate using RMSD.

From the problem you describe, you indeed need symmetry corrections, otherwise you will get erroneous results (especially if the atoms are not correctly ordered compared to your reference). `rmsd.symmrmsd` is indeed able to compute the correct RMSD if atoms are not in the correct order, but it needs the bond information.

I did not look at your structure, but @davidoskky was very helpful and did it, providing further insight and suggestions.

What is puzzling me at this point is the following: why your conformer generator only outputs `.xyz` files? I assume you need the bond information to sample the conformers?

As @davidoskky pointed out, inferring bonds is error-prone, so if you have this information I'd make use of it. If you really don't, you will have to infer them. `xyz2mol` is a good tool, and now it is also [integrated in RDKit](https://greglandrum.github.io/rdkit-blog/posts/2022-12-18-introducing-rdDetermineBonds.html), which is the `rdDetermineBonds` you mentioned.
 
FYI, there is also a very simple (and therefore not at all robust!) function in `spyrmsd` to infer bonds:

https://github.com/RMeli/spyrmsd/blob/b5532dd1b677a686c9d31c7bf39446e0a66e0af8/spyrmsd/graph.py#L42-L94

> Now correctly give the connectivity matrix but still furnish the same error line.

If you still get the `UserWarning` it means that one or more atoms are not connected. Or that you have a missing bonds connecting to fragments of the same molecule. Please double check the connectivity an make sure it's correct.

**Comment by RMeli** [comment]
PR #90 adds some details for `NotImplementedError` exceptions. In this particular case, the next release of `spyrmsd` would result in the following error message:
```
NotImplementedError: Format 'XYZ' is currently not supported with RDKit.
```

**Comment by RMeli** [comment]
Closing since #90 introduces a clear message for the error.

Please feel free to continue this thread of discussion here, if needed!
